M48
; DRILL file {KiCad 7.0.8} date Wed May  8 13:20:16 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-05-08T13:20:16-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0240
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1579
%
G90
G05
T1
X2.8175Y-3.1172
X2.8175Y-3.4282
X2.8445Y-3.1172
X2.8445Y-3.4282
T2
X3.7476Y-5.6891
X7.1976Y-5.6891
T0
M30
